[build]
builder = "nixpacks"
buildCommand = "apt-get update && apt-get install -y python3 python3-pip && cd philoagents-api && pip install uv && uv venv .venv && . .venv/bin/activate && uv pip install -e ."

[deploy]
startCommand = "make infrastructure-up"
healthcheckPath = "/docs"
healthcheckTimeout = 100

[env]
PYTHON_VERSION = "3.11"