[build]
builder = "nixpacks"
buildCommand = "apt-get update && apt-get install -y docker.io docker-compose && docker-compose up -d"

[deploy]
startCommand = "echo 1"
healthcheckPath = "/doc"
healthcheckTimeout = 100

[env]
PYTHON_VERSION = "3.11"